### ISSUE TITLE
[bug] Authentication issues between the proxy and the hub when restarting the hub

### ISSUE THREAD

**Issue by rsarm** [eth-cscs/firecrestspawner#17]
When the hub is shutdown from the Admin tab sometimes it doesn't manage to come restart because authentication issues between the hub and the proxy:
```
[I 2024-07-22 11:25:50.641 JupyterHub app:2885] Running JupyterHub version 4.1.5
[I 2024-07-22 11:25:50.641 JupyterHub app:2915] Using Authenticator: builtins.GenericOAuthenticatorCSCS
[I 2024-07-22 11:25:50.641 JupyterHub app:2915] Using Spawner: firecrestspawner.spawner.SlurmSpawner
[I 2024-07-22 11:25:50.641 JupyterHub app:2915] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-4.1.5
[I 2024-07-22 11:25:50.646 JupyterHub app:1683] Loading cookie_secret from /home/juhu/jupyterhub_cookie_secret
[W 2024-07-22 11:25:50.704 JupyterHub oauth2:1055] GenericOAuthenticatorCSCS.username_key is deprecated in GenericOAuthenticatorCSCS 16.0.0, use GenericOAuthenticatorCSCS.username_claim instead
[I 2024-07-22 11:25:50.707 JupyterHub app:2005] Not using allowed_users. Any authenticated user will be allowed.
[I 2024-07-22 11:25:50.729 JupyterHub app:2954] Initialized 0 spawners in 0.004 seconds
[I 2024-07-22 11:25:50.734 JupyterHub metrics:279] Found 1 active users in the last ActiveUserPeriods.twenty_four_hours
[I 2024-07-22 11:25:50.734 JupyterHub metrics:279] Found 1 active users in the last ActiveUserPeriods.seven_days
[I 2024-07-22 11:25:50.735 JupyterHub metrics:279] Found 1 active users in the last ActiveUserPeriods.thirty_days
[I 2024-07-22 11:25:50.735 JupyterHub app:3168] Not starting proxy
[E 2024-07-22 11:25:50.740 JupyterHub proxy:950] api_request to proxy failed: HTTP 403: Forbidden
[E 2024-07-22 11:25:50.740 JupyterHub app:3408]
    Traceback (most recent call last):
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/app.py", line 3406, in launch_instance_async
        await self.start()
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/app.py", line 3172, in start
        await self.proxy.get_all_routes()
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/proxy.py", line 990, in get_all_routes
        resp = await self.api_request('', client=client)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/proxy.py", line 954, in api_request
        result = await exponential_backoff(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/utils.py", line 241, in exponential_backoff
        ret = await maybe_future(pass_func(*args, **kwargs))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/proxy.py", line 937, in _wait_for_api_request
        return await client.fetch(req)
               ^^^^^^^^^^^^^^^^^^^^^^^
    tornado.httpclient.HTTPClientError: HTTP 403: Forbidden
```

The log of the proxy has many of these
```
11:25:04.654 [ConfigProxy] warn: 403 GET /api/routes
11:25:20.659 [ConfigProxy] warn: 403 GET /api/routes
11:25:32.131 [ConfigProxy] error: 503 GET /admin connect ECONNREFUSED 10.42.11.231:8081
11:25:32.168 [ConfigProxy] error: 503 GET /favicon.ico connect ECONNREFUSED 10.42.11.231:8081
```

The issue happened once while staring for the first time after deploying.

**Comment by rsarm** [comment]
I think the problem was that there was a typo in the part of `secret.yaml` that checks if the `configProxyAuthToken` is defined:
```yaml
{{- if $existingSecret }}
  {{- $token = index $existingSecret.data "configProxyAuthToken"}}
{{- end -}}
```
Fixing the typo should solve the problem.

That's fixed in chart-v0.6.2. Now checking if the issue persists.

**Comment by rsarm** [comment]
Fixing the typo above seems to have solve the issue.

**Comment by rsarm** [comment]
The main problem was not the thing above, but that the value of configProxyAuthToken defined in the secret changes with argocd deployments. Apparently, argocd may re-render helm charts during sync operations, even if one hasn't made any changes in the repo. It doesn't happen with helm deployments.
