### ISSUE TITLE
[bug] `spawner.start()` returns `None` ip

### ISSUE THREAD

**Issue by rsarm** [eth-cscs/firecrestspawner#18]
```log
[I 2024-07-23 09:21:59.753 JupyterHub spawner:377] Notebook server job 17088 started at :50396
[E 2024-07-23 09:21:59.754 JupyterHub user:887] Unhandled error starting sarafael's server: The 'ip' trait of a Server instance expected a unicode string, not the NoneType None.
    Traceback (most recent call last):
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/user.py", line 818, in spawn
        server.ip = urlinfo.hostname
        ^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 716, in __set__
        self.set(obj, value)
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 690, in set
        new_value = self._validate(obj, value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 722, in _validate
        value = self.validate(obj, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 2945, in validate
        self.error(obj, value)
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 831, in error
        raise TraitError(e)
    traitlets.traitlets.TraitError: The 'ip' trait of a Server instance expected a unicode string, not the NoneType None.

[I 2024-07-23 09:22:00.996 JupyterHub spawner:388] Stopping server job 17088
[I 2024-07-23 09:22:00.996 JupyterHub spawner:278] Cancelling job 17088
[I 2024-07-23 09:22:01.199 JupyterHub spawner:280] firecREST: Canceling job
Task exception was never retrieved
future: <Task finished name='Task-813' coro=<BaseHandler.spawn_single_user() done, defined at /opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/handlers/base.py:971> exception=HTTPError()>
Traceback (most recent call last):
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 1178, in spawn_single_user
    await gen.with_timeout(
TimeoutError: Timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 1212, in spawn_single_user
    raise web.HTTPError(
tornado.web.HTTPError: HTTP 500: Internal Server Error (Spawner failed to start [status=1]. The logs for sarafael may contain details.)
[E 2024-07-23 09:22:04.067 JupyterHub gen:629] Exception in Future <Task finished name='Task-814' coro=<BaseHandler.spawn_single_user.<locals>.finish_user_spawn() done, defined at /opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/handlers/base.py:1081> exception=TraitError("The 'ip' trait of a Server instance expected a unicode string, not the NoneType None.")> after timeout
    Traceback (most recent call last):
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/tornado/gen.py", line 624, in error_callback
        future.result()
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 1088, in finish_user_spawn
        await spawn_future
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/user.py", line 905, in spawn
        raise e
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/jupyterhub/user.py", line 818, in spawn
        server.ip = urlinfo.hostname
        ^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 716, in __set__
        self.set(obj, value)
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 690, in set
        new_value = self._validate(obj, value)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 722, in _validate
        value = self.validate(obj, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 2945, in validate
        self.error(obj, value)
      File "/opt/conda/envs/py311/lib/python3.11/site-packages/traitlets/traitlets.py", line 831, in error
        raise TraitError(e)
    traitlets.traitlets.TraitError: The 'ip' trait of a Server instance expected a unicode string, not the NoneType None.

[I 2024-07-23 09:22:04.071 JupyterHub log:192] 200 GET /hub/api/users/sarafael/server/progress?_xsrf=[secret] (sarafael@148.187.134.53) 11130.63ms
```

**Comment by rsarm** [comment]
Haven't managed to reproduce this in a long time. Closing it.
